### ISSUE TITLE
Cálculo del valor de la cosecha 

### ISSUE THREAD

**Issue by morevi** [francisco3207/IVProyecto#9]
Queremos calcular el valor de una cosecha.
No sabemos nada sobre el Producto para el que querremos obtener una predicción del precio.

Sabemos que:
- El valor del producto depende del precio de venta ofrecido por la cooperativa (lo que la predicción pretende maximizar)
- La cantidad de aceite dependerá del rendimiento y de la cantidad de aceituna recogida.
- El rendimiento NO se calcula: la cooperativa se encargará de proporcionar este dato.
- El precio de venta NO se calcula: la cooperativa proporciona este valor según la oferta y demanda.
- El histórico de precios de venta contendrá los precios de la cooperativa según la fecha.

Tendremos que recoger la información que representa un producto en una clase Producto.

El producto puede ser definido por el tipo de aceituna y la cantidad recogida en kgs.
A partir de esos datos y el rendimiento proporcionado por la cooperativa, se puede calcular la cantidad de aceite que se producirá.

 En este caso, _Producto_ será un objeto-valor, no tienen una identidad (pueden existir 2 productos/cosechas/cultivos con los mismos atributos), sino que son representados completamente por sus atributos, que, una vez asignados, son inmutables. Además el ciclo de vida de un _Producto_ abarcará solo el tiempo de realizar las predicciones.

Se avanza:
- #7
- [M1](https://github.com/francisco3207/IVProyecto/milestone/2)

Tareas:
- [x] clase producto
- [x] atributos: kgs recogidos y tipo de aceituna
- [x] metodos: calcular_aceite

**Comment by morevi** [comment]
**Esto es basicamente un paste de la documentación añadida**

Para representar los cultivos, se ha creado una clase _producto_.
Se ha llamado _producto_, ya que es la palabra que mejor define al cultivo tanto durante su crecimiento como después de su recogida.

En este caso, _producto_ será un objeto-valor, no tienen una identidad (pueden existir 2 productos/cosechas/cultivos con los mismos atributos), sino que son representados completamente por sus atributos, que, una vez asignados, son inmutables.

Esta clase, respaldará la [HU1](https://github.com/francisco3207/IVProyecto/issues/7), porque contendrá valores necesarios para poder calcular el valor de la cosecha.

Mediante el uso de una clase _Producto_, que contenga información sobre el tipo de aceituna plantada y sobre la cosecha, podremos almacenar los datos que definan una cosecha.
- tipo
- rendimiento_base
- fecha_plantado
- kgs_recogidos
- fecha_recogida

Además a partir de esos datos y otros datos, ajenos a una cosecha en concreto (fecha sobre la que predecir, mercado actual) podremos calcular los valores necesarios que servirán para realizar las predicciones. Hablo de los métodos:
- predecir_rendimiento, a partir de los datos de nuestra cosecha y el momento sobre el que predecir
- calcular_aceite
- calcular_beneficio, a partir de los datos de la cosecha y del mercado, es el objetivo de [M1](https://github.com/francisco3207/IVProyecto/milestone/2)

**Comment by francisco3207** [comment]
La variable fecha_plantado no tiene mucha utilidad, ya que un olivo puede durar 2000 años y su vida util ronda los 50 años

**Comment by JJ** [comment]
¿Estás hablando de producción y no de producto? Aparte que me da la impresión de que estás metiendo en una sola clase lo que debería estar en varias clases.

**Comment by morevi** [comment]
El rendimiento NO se calcula
